import type { ComponentProps, ComponentType } from "react";
import {
  Star,
  Heart,
  HeartShine,
  Home,
  Settings,
  Bell,
  Magnifer,
  CheckCircle,
  Checklist,
  CloseCircle,
  AddCircle,
  MinusCircle,
  InfoCircle,
  QuestionCircle,
  DangerTriangle,
  DangerCircle,
  Lightbulb,
  Flag,
  Flag2,
  Bookmark,
  Pin,
  MapPoint,
  Eye,
  Lock,
  LockKeyhole,
  Key,
  Shield,
  ShieldCheck,
  Fire,
  Crown,
  CupStar,
  MedalStar,
  Bolt,
  MagicStick3,
  Confetti,
  Rocket,
  Target,
  Folder,
  Document,
  DocumentText,
  DocumentAdd,
  Notebook,
  Notes,
  ClipboardText,
  ClipboardCheck,
  Calendar,
  CalendarMark,
  Pen,
  PenNewSquare,
  Paperclip,
  Archive,
  TrashBinMinimalistic,
  Download,
  Upload,
  Copy,
  Diskette,
  Printer,
  Letter,
  ChatRound,
  ChatRoundLine,
  Phone,
  Inbox,
  Share,
  LinkMinimalistic,
  Gallery,
  Camera,
  Videocamera,
  MusicNote,
  Play,
  PlayCircle,
  Microphone,
  HeadphonesRound,
  User,
  UserCircle,
  UsersGroupRounded,
  Cart,
  Wallet,
  DollarMinimalistic,
  Tag,
  Gift,
  Sun,
  Moon,
  Cloud,
  Snowflake,
  Leaf,
  Smartphone,
  Laptop,
  Monitor,
  Server,
  Database,
  Cpu,
  Bug,
  Code,
  CodeSquare,
  ClockCircle,
  Stopwatch,
  History,
  Map,
  Compass,
  Global,
  Plain,
  ChefHat,
  CupHot,
  Donut,
  Wineglass,
  Football,
  Basketball,
  Dumbbell,
  Running,
  TestTube,
  Atom,
  Bag,
  Ghost,
  Cat,
  GraphUp,
  ChartSquare,
  PieChart,
  Hashtag,
  Card,
  Bluetooth,
  SmileCircle,
} from "@solar-icons/react/ssr";

/** All Solar icons share one props shape; type against any of them. */
export type SolarIcon = ComponentType<ComponentProps<typeof Star>>;

/**
 * Curated, CLOSED SET of insertable icons. An icon block stores only a KEY from
 * this registry; rendering goes through `iconComponent(key)`, which returns null
 * for anything not in the table. Keeping it a whitelist (not arbitrary names)
 * matches the editor's XSS-safe-by-construction philosophy and keeps the bundle
 * to a sensible subset of the ~1,400-icon Solar set.
 */
export const ICON_REGISTRY: Record<string, SolarIcon> = {
  Star,
  Heart,
  HeartShine,
  Home,
  Settings,
  Bell,
  Magnifer,
  CheckCircle,
  Checklist,
  CloseCircle,
  AddCircle,
  MinusCircle,
  InfoCircle,
  QuestionCircle,
  DangerTriangle,
  DangerCircle,
  Lightbulb,
  Flag,
  Flag2,
  Bookmark,
  Pin,
  MapPoint,
  Eye,
  Lock,
  LockKeyhole,
  Key,
  Shield,
  ShieldCheck,
  Fire,
  Crown,
  CupStar,
  MedalStar,
  Bolt,
  MagicStick3,
  Confetti,
  Rocket,
  Target,
  Folder,
  Document,
  DocumentText,
  DocumentAdd,
  Notebook,
  Notes,
  ClipboardText,
  ClipboardCheck,
  Calendar,
  CalendarMark,
  Pen,
  PenNewSquare,
  Paperclip,
  Archive,
  TrashBinMinimalistic,
  Download,
  Upload,
  Copy,
  Diskette,
  Printer,
  Letter,
  ChatRound,
  ChatRoundLine,
  Phone,
  Inbox,
  Share,
  LinkMinimalistic,
  Gallery,
  Camera,
  Videocamera,
  MusicNote,
  Play,
  PlayCircle,
  Microphone,
  HeadphonesRound,
  User,
  UserCircle,
  UsersGroupRounded,
  Cart,
  Wallet,
  DollarMinimalistic,
  Tag,
  Gift,
  Sun,
  Moon,
  Cloud,
  Snowflake,
  Leaf,
  Smartphone,
  Laptop,
  Monitor,
  Server,
  Database,
  Cpu,
  Bug,
  Code,
  CodeSquare,
  ClockCircle,
  Stopwatch,
  History,
  Map,
  Compass,
  Global,
  Plain,
  ChefHat,
  CupHot,
  Donut,
  Wineglass,
  Football,
  Basketball,
  Dumbbell,
  Running,
  TestTube,
  Atom,
  Bag,
  Ghost,
  Cat,
  GraphUp,
  ChartSquare,
  PieChart,
  Hashtag,
  Card,
  Bluetooth,
  SmileCircle,
};

/** Whitelist lookup — returns the component for a known key, else null. */
export function iconComponent(key: string | undefined | null): SolarIcon | null {
  if (!key) return null;
  return ICON_REGISTRY[key] ?? null;
}

/** Split a PascalCase/number icon key into human words for label + search. */
function humanize(key: string): string {
  return key
    .replace(/([a-z])([A-Z0-9])/g, "$1 $2")
    .replace(/([0-9])([A-Za-z])/g, "$1 $2")
    .trim();
}

export interface IconMeta {
  key: string;
  label: string;
  keywords: string[];
}

/** Pickable icons with derived labels + search keywords. */
export const ICON_LIST: IconMeta[] = Object.keys(ICON_REGISTRY).map((key) => {
  const label = humanize(key);
  return { key, label, keywords: label.toLowerCase().split(/\s+/) };
});

/** Filter the icon list by a free-text query (matches key + derived words). */
export function filterIcons(query: string): IconMeta[] {
  const q = query.trim().toLowerCase();
  if (!q) return ICON_LIST;
  return ICON_LIST.filter(
    (i) =>
      i.key.toLowerCase().includes(q) ||
      i.keywords.some((k) => k.includes(q)),
  );
}
